### ISSUE TITLE
Pipeline Initialisation Bug

### ISSUE THREAD

**Issue by VasilyKokorev** [gbrammer/msaexp#34]
When calling the `pipeline.NirspecPipeline`, specifying `source_ids` leads to the following error: `local variable 'six' was referenced before assignment`. 

The issue was traced to the `pad_msa_metafile` function and happens when this line is executed - `this_source_ids = np.unique(msa.shutter_table['source_id'][six])` 

If `source_ids` are not specified in`pipeline.NirspecPipeline`, the code runs normally.

**Comment by gbrammer** [comment]
This should be resolved now with https://github.com/gbrammer/msaexp/pull/35.
